AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'ofx_kit.gemspec'

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/NonAtomicFileOperation:
  Enabled: false
